[Variables]


;=====================|   COLORS   |=====================


BackgroundColor=255,255,255


AccentColor=646464


FontMainColor=100,100,100
FontShadowColor=50,50,50,100
MistGrayColor=196,196,196
ImageOuterColor=161,161,161,255
ImageFrameColor=143,143,143,255
ImageInnerColor=0,0,0,255

GreenColour=57,191,109,255
RedColour=191,46,46,255


ObjectMainColor=100,100,100
ObjectShadowColor=200,200,200


;=====================|   HDDS   |====================


Disk1=C
Disk2=F
Disk3=G
Disk4=I


;=====================|   DOCK   |====================


DockGreyscale=0


ColorSwitch=on


;=====================|   PLAYER   |====================


PlayerName=iTunes


;=====================|   WEATHER   |====================


Location=FRXX1074
Units=m


UnitsSwitch=C


;=====================|   WEATHER   |====================


IP=1
IPMasked=0


MaskSwitch=on
