/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skripsiMaven.Sfile.FrameList;

import com.skripsiMaven.Sfile.Script.Export_Script;
import com.skripsiMaven.Sfile.Script.Options_Script;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TooManyListenersException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

/**
 *
 * @author alexa
 */
public class Main_Frame extends javax.swing.JFrame {

    int xMouseInDeskTopBackground;
    int yMouseInDeskTopBackground;
    int x2;
    int y2;

    int xImage_POS;
    int yImage_POS;
    JFileChooser chooser;
    String choosertitle;

    double Coor_ScaleX = 1.55;
    double Coor_ScaleY = 3.65;
    private String path_local = "src/images/";
    JLabel jlabels[] = new JLabel[10];
    String[] jlabels_coordinat = new String[10];

    private int sum_Labels = 0;
    List<Map<String, Object>> List_jlabels_statField_label = new ArrayList<Map<String, Object>>();
    List<Map<String, Object>> List_jlabels_base_sample = new ArrayList<Map<String, Object>>();

    JOptionPane alertBox = new JOptionPane();
    Options_Script opt = new Options_Script();

    /**
     * Creates new form TestLayout
     */
    public Main_Frame() {
        initComponents();
        setResizable(false);
        customInit();
//        setUndecorated(true);
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        drop_zone_panel = new DropPane();
        Label_Drop_Image = new javax.swing.JLabel();
        IMG_OPTIONS = new javax.swing.JPanel();
        RESIZE_LABEL_IMG = new javax.swing.JLabel();
        Change_Color_IMG = new javax.swing.JLabel();
        Jlabel_OPTIONS_IMG_ID = new javax.swing.JLabel();
        SETWIDTH_HEIGHT_DIALOG = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SET_WIDTH_INPUT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SET_HEIGHT_INPUT = new javax.swing.JTextField();
        RESIZE_ID = new javax.swing.JLabel();
        SAVE_W_H_LABEL = new javax.swing.JLabel();
        FILE_LABEL = new javax.swing.JPanel();
        EXIT_APP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        INSERT_LABEL = new javax.swing.JLabel();
        Choose_File_Panel = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        checkCustomPath = new javax.swing.JToggleButton();
        FILE_OPTIONS = new javax.swing.JPanel();
        FILE_SAVE = new javax.swing.JLabel();
        Change_Color_Label1 = new javax.swing.JLabel();
        Jlabel_OPTIONS_ID1 = new javax.swing.JLabel();
        INSERT_OPTIONS = new javax.swing.JPanel();
        IN_RAM_METER_LABEL = new javax.swing.JLabel();
        Jlabel_OPTIONS_ID2 = new javax.swing.JLabel();
        IN_CPU_METER_LABEL = new javax.swing.JLabel();
        COLOR_PICKER_PANEL = new javax.swing.JPanel();
        jColorChooser1 = new javax.swing.JColorChooser();
        LABEL_OPTIONS = new javax.swing.JPanel();
        Change_Color_LABEL = new javax.swing.JLabel();
        Jlabel_OPTIONS_LABEL_ID = new javax.swing.JLabel();
        Font_Styling_Label = new javax.swing.JLabel();
        SETFONTSIZE_DIALOG = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        SET_FONTSIZE_INPUT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SET_HEIGHT_INPUT1 = new javax.swing.JTextField();
        FONTSTYLING_ID = new javax.swing.JLabel();
        SAVE_FONTSTYLING_LABEL = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        drop_zone_panel.setBackground(new java.awt.Color(255, 255, 255));
        drop_zone_panel.setMaximumSize(new java.awt.Dimension(1200, 800));
        drop_zone_panel.setMinimumSize(new java.awt.Dimension(1200, 800));
        drop_zone_panel.setPreferredSize(new java.awt.Dimension(1200, 800));
        drop_zone_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drop_zone_panelMouseDragged(evt);
            }
        });
        drop_zone_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drop_zone_panelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drop_zone_panelMousePressed(evt);
            }
        });
        drop_zone_panel.setLayout(null);

        Label_Drop_Image.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Label_Drop_Image.setForeground(new java.awt.Color(0, 0, 0));
        Label_Drop_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Drop_Image.setText("Drop an Image");
        drop_zone_panel.add(Label_Drop_Image);
        Label_Drop_Image.setBounds(360, 400, 460, 60);

        IMG_OPTIONS.setBackground(new java.awt.Color(27, 38, 44));
        IMG_OPTIONS.setMaximumSize(new java.awt.Dimension(120, 140));

        RESIZE_LABEL_IMG.setForeground(new java.awt.Color(187, 225, 250));
        RESIZE_LABEL_IMG.setText("Resize");
        RESIZE_LABEL_IMG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RESIZE_LABEL_IMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RESIZE_LABEL_IMGMouseClicked(evt);
            }
        });

        Change_Color_IMG.setForeground(new java.awt.Color(187, 225, 250));
        Change_Color_IMG.setText("Change Color");
        Change_Color_IMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Change_Color_IMGMouseClicked(evt);
            }
        });

        Jlabel_OPTIONS_IMG_ID.setText("jlabelID");

        javax.swing.GroupLayout IMG_OPTIONSLayout = new javax.swing.GroupLayout(IMG_OPTIONS);
        IMG_OPTIONS.setLayout(IMG_OPTIONSLayout);
        IMG_OPTIONSLayout.setHorizontalGroup(
            IMG_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IMG_OPTIONSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IMG_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Change_Color_IMG, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(RESIZE_LABEL_IMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jlabel_OPTIONS_IMG_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        IMG_OPTIONSLayout.setVerticalGroup(
            IMG_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IMG_OPTIONSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RESIZE_LABEL_IMG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Change_Color_IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Jlabel_OPTIONS_IMG_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        drop_zone_panel.add(IMG_OPTIONS);
        IMG_OPTIONS.setBounds(0, 310, 120, 140);
        IMG_OPTIONS.setVisible(false);

        SETWIDTH_HEIGHT_DIALOG.setBackground(new java.awt.Color(27, 38, 44));
        SETWIDTH_HEIGHT_DIALOG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, null, null));

        jLabel2.setForeground(new java.awt.Color(187, 225, 250));
        jLabel2.setText("Set Width :");

        jPanel1.setBackground(new java.awt.Color(15, 76, 117));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 225, 250));
        jLabel3.setText("Width and Height Setting");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        SET_WIDTH_INPUT.setBackground(new java.awt.Color(27, 38, 44));
        SET_WIDTH_INPUT.setForeground(new java.awt.Color(187, 225, 250));
        SET_WIDTH_INPUT.setText("0");

        jLabel4.setForeground(new java.awt.Color(187, 225, 250));
        jLabel4.setText("Set Height :");

        SET_HEIGHT_INPUT.setBackground(new java.awt.Color(27, 38, 44));
        SET_HEIGHT_INPUT.setForeground(new java.awt.Color(187, 225, 250));
        SET_HEIGHT_INPUT.setText("0");

        RESIZE_ID.setText("ID");

        SAVE_W_H_LABEL.setBackground(new java.awt.Color(27, 38, 44));
        SAVE_W_H_LABEL.setForeground(new java.awt.Color(187, 225, 250));
        SAVE_W_H_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SAVE_W_H_LABEL.setText("Save");
        SAVE_W_H_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAVE_W_H_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAVE_W_H_LABELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SETWIDTH_HEIGHT_DIALOGLayout = new javax.swing.GroupLayout(SETWIDTH_HEIGHT_DIALOG);
        SETWIDTH_HEIGHT_DIALOG.setLayout(SETWIDTH_HEIGHT_DIALOGLayout);
        SETWIDTH_HEIGHT_DIALOGLayout.setHorizontalGroup(
            SETWIDTH_HEIGHT_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(RESIZE_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createSequentialGroup()
                .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SET_HEIGHT_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(SET_WIDTH_INPUT)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SAVE_W_H_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SETWIDTH_HEIGHT_DIALOGLayout.setVerticalGroup(
            SETWIDTH_HEIGHT_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RESIZE_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SET_WIDTH_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SETWIDTH_HEIGHT_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SET_HEIGHT_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVE_W_H_LABEL))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        drop_zone_panel.add(SETWIDTH_HEIGHT_DIALOG);
        SETWIDTH_HEIGHT_DIALOG.setBounds(-120, 460, 240, 160);

        FILE_LABEL.setBackground(new java.awt.Color(27, 38, 44));
        FILE_LABEL.setPreferredSize(new java.awt.Dimension(1920, 50));

        EXIT_APP.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        EXIT_APP.setForeground(new java.awt.Color(255, 0, 51));
        EXIT_APP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EXIT_APP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_sign_out_30px.png"))); // NOI18N
        EXIT_APP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXIT_APPMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 225, 250));
        jLabel1.setText("File");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        INSERT_LABEL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        INSERT_LABEL.setForeground(new java.awt.Color(187, 225, 250));
        INSERT_LABEL.setText("Insert");
        INSERT_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INSERT_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INSERT_LABELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FILE_LABELLayout = new javax.swing.GroupLayout(FILE_LABEL);
        FILE_LABEL.setLayout(FILE_LABELLayout);
        FILE_LABELLayout.setHorizontalGroup(
            FILE_LABELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FILE_LABELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(INSERT_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 962, Short.MAX_VALUE)
                .addComponent(EXIT_APP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FILE_LABELLayout.setVerticalGroup(
            FILE_LABELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FILE_LABELLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(FILE_LABELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EXIT_APP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FILE_LABELLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(FILE_LABELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(INSERT_LABEL))))
                .addGap(8, 8, 8))
        );

        drop_zone_panel.add(FILE_LABEL);
        FILE_LABEL.setBounds(0, 0, 1200, 50);

        jFileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.setAcceptAllFileFilterUsed(false);

        javax.swing.GroupLayout Choose_File_PanelLayout = new javax.swing.GroupLayout(Choose_File_Panel);
        Choose_File_Panel.setLayout(Choose_File_PanelLayout);
        Choose_File_PanelLayout.setHorizontalGroup(
            Choose_File_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Choose_File_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        Choose_File_PanelLayout.setVerticalGroup(
            Choose_File_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Choose_File_PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        drop_zone_panel.add(Choose_File_Panel);
        Choose_File_Panel.setBounds(1240, 140, 700, 540);

        checkCustomPath.setText("Save File");
        checkCustomPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCustomPathActionPerformed(evt);
            }
        });
        drop_zone_panel.add(checkCustomPath);
        checkCustomPath.setBounds(1040, 760, 160, 32);

        FILE_OPTIONS.setBackground(new java.awt.Color(27, 38, 44));
        FILE_OPTIONS.setMaximumSize(new java.awt.Dimension(120, 140));

        FILE_SAVE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FILE_SAVE.setForeground(new java.awt.Color(187, 225, 250));
        FILE_SAVE.setText("Save Project");
        FILE_SAVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FILE_SAVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FILE_SAVEMouseClicked(evt);
            }
        });

        Change_Color_Label1.setForeground(new java.awt.Color(187, 225, 250));
        Change_Color_Label1.setText("Choose File");
        Change_Color_Label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Change_Color_Label1MouseClicked(evt);
            }
        });

        Jlabel_OPTIONS_ID1.setText("jlabelID");

        javax.swing.GroupLayout FILE_OPTIONSLayout = new javax.swing.GroupLayout(FILE_OPTIONS);
        FILE_OPTIONS.setLayout(FILE_OPTIONSLayout);
        FILE_OPTIONSLayout.setHorizontalGroup(
            FILE_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FILE_OPTIONSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FILE_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Change_Color_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FILE_SAVE, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(Jlabel_OPTIONS_ID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        FILE_OPTIONSLayout.setVerticalGroup(
            FILE_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FILE_OPTIONSLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(FILE_SAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Change_Color_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(Jlabel_OPTIONS_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        drop_zone_panel.add(FILE_OPTIONS);
        FILE_OPTIONS.setBounds(0, 50, 110, 250);
        IMG_OPTIONS.setVisible(false);

        INSERT_OPTIONS.setBackground(new java.awt.Color(27, 38, 44));
        INSERT_OPTIONS.setMaximumSize(new java.awt.Dimension(120, 140));

        IN_RAM_METER_LABEL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IN_RAM_METER_LABEL.setForeground(new java.awt.Color(187, 225, 250));
        IN_RAM_METER_LABEL.setText("Insert RAM Meter");
        IN_RAM_METER_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN_RAM_METER_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IN_RAM_METER_LABELMouseClicked(evt);
            }
        });

        Jlabel_OPTIONS_ID2.setText("jlabelID");

        IN_CPU_METER_LABEL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IN_CPU_METER_LABEL.setForeground(new java.awt.Color(187, 225, 250));
        IN_CPU_METER_LABEL.setText("Insert CPU Meter");
        IN_CPU_METER_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IN_CPU_METER_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IN_CPU_METER_LABELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout INSERT_OPTIONSLayout = new javax.swing.GroupLayout(INSERT_OPTIONS);
        INSERT_OPTIONS.setLayout(INSERT_OPTIONSLayout);
        INSERT_OPTIONSLayout.setHorizontalGroup(
            INSERT_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INSERT_OPTIONSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(INSERT_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IN_RAM_METER_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jlabel_OPTIONS_ID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IN_CPU_METER_LABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap())
        );
        INSERT_OPTIONSLayout.setVerticalGroup(
            INSERT_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INSERT_OPTIONSLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(IN_RAM_METER_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IN_CPU_METER_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(Jlabel_OPTIONS_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        drop_zone_panel.add(INSERT_OPTIONS);
        INSERT_OPTIONS.setBounds(110, 50, 170, 250);
        IMG_OPTIONS.setVisible(false);

        javax.swing.GroupLayout COLOR_PICKER_PANELLayout = new javax.swing.GroupLayout(COLOR_PICKER_PANEL);
        COLOR_PICKER_PANEL.setLayout(COLOR_PICKER_PANELLayout);
        COLOR_PICKER_PANELLayout.setHorizontalGroup(
            COLOR_PICKER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(COLOR_PICKER_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        COLOR_PICKER_PANELLayout.setVerticalGroup(
            COLOR_PICKER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(COLOR_PICKER_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        drop_zone_panel.add(COLOR_PICKER_PANEL);
        COLOR_PICKER_PANEL.setBounds(1210, 50, 670, 390);

        LABEL_OPTIONS.setBackground(new java.awt.Color(27, 38, 44));
        LABEL_OPTIONS.setMaximumSize(new java.awt.Dimension(120, 140));

        Change_Color_LABEL.setForeground(new java.awt.Color(187, 225, 250));
        Change_Color_LABEL.setText("Change Color");
        Change_Color_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Change_Color_LABELMouseClicked(evt);
            }
        });

        Jlabel_OPTIONS_LABEL_ID.setText("jlabelID");

        Font_Styling_Label.setForeground(new java.awt.Color(187, 225, 250));
        Font_Styling_Label.setText("Font Styling");
        Font_Styling_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Font_Styling_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LABEL_OPTIONSLayout = new javax.swing.GroupLayout(LABEL_OPTIONS);
        LABEL_OPTIONS.setLayout(LABEL_OPTIONSLayout);
        LABEL_OPTIONSLayout.setHorizontalGroup(
            LABEL_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LABEL_OPTIONSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LABEL_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Change_Color_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(Jlabel_OPTIONS_LABEL_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Font_Styling_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        LABEL_OPTIONSLayout.setVerticalGroup(
            LABEL_OPTIONSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LABEL_OPTIONSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Change_Color_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Font_Styling_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Jlabel_OPTIONS_LABEL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        drop_zone_panel.add(LABEL_OPTIONS);
        LABEL_OPTIONS.setBounds(120, 310, 120, 140);
        IMG_OPTIONS.setVisible(false);

        SETFONTSIZE_DIALOG.setBackground(new java.awt.Color(27, 38, 44));
        SETFONTSIZE_DIALOG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, null, null));

        jLabel5.setForeground(new java.awt.Color(187, 225, 250));
        jLabel5.setText("Set Font Size");

        jPanel2.setBackground(new java.awt.Color(15, 76, 117));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 225, 250));
        jLabel6.setText("Font Styling Setting");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        SET_FONTSIZE_INPUT.setBackground(new java.awt.Color(27, 38, 44));
        SET_FONTSIZE_INPUT.setForeground(new java.awt.Color(187, 225, 250));
        SET_FONTSIZE_INPUT.setText("0");

        jLabel7.setForeground(new java.awt.Color(187, 225, 250));
        jLabel7.setText("Set Height :");

        SET_HEIGHT_INPUT1.setBackground(new java.awt.Color(27, 38, 44));
        SET_HEIGHT_INPUT1.setForeground(new java.awt.Color(187, 225, 250));
        SET_HEIGHT_INPUT1.setText("0");

        FONTSTYLING_ID.setText("ID");

        SAVE_FONTSTYLING_LABEL.setBackground(new java.awt.Color(27, 38, 44));
        SAVE_FONTSTYLING_LABEL.setForeground(new java.awt.Color(187, 225, 250));
        SAVE_FONTSTYLING_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SAVE_FONTSTYLING_LABEL.setText("Save");
        SAVE_FONTSTYLING_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAVE_FONTSTYLING_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAVE_FONTSTYLING_LABELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SETFONTSIZE_DIALOGLayout = new javax.swing.GroupLayout(SETFONTSIZE_DIALOG);
        SETFONTSIZE_DIALOG.setLayout(SETFONTSIZE_DIALOGLayout);
        SETFONTSIZE_DIALOGLayout.setHorizontalGroup(
            SETFONTSIZE_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SETFONTSIZE_DIALOGLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(FONTSTYLING_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(SETFONTSIZE_DIALOGLayout.createSequentialGroup()
                .addGroup(SETFONTSIZE_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SETFONTSIZE_DIALOGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SETFONTSIZE_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SET_HEIGHT_INPUT1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(SET_FONTSIZE_INPUT)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SAVE_FONTSTYLING_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SETFONTSIZE_DIALOGLayout.setVerticalGroup(
            SETFONTSIZE_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETFONTSIZE_DIALOGLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SETFONTSIZE_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FONTSTYLING_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SET_FONTSIZE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SETFONTSIZE_DIALOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SET_HEIGHT_INPUT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVE_FONTSTYLING_LABEL))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        drop_zone_panel.add(SETFONTSIZE_DIALOG);
        SETFONTSIZE_DIALOG.setBounds(280, 50, 240, 160);

        getContentPane().add(drop_zone_panel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void customInit() {
        SETWIDTH_HEIGHT_DIALOG.setVisible(false);
        Choose_File_Panel.setVisible(false);
        INSERT_OPTIONS.setVisible(false);
        FILE_OPTIONS.setVisible(false);
        COLOR_PICKER_PANEL.setVisible(false);
        LABEL_OPTIONS.setVisible(false);
        SETFONTSIZE_DIALOG.setVisible(false);
    }

    private void drop_zone_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drop_zone_panelMousePressed
        System.out.println("Jpanel: MOUSE PRESS");
//        xMouseInDeskTopBackground = evt.getX();
//        yMouseInDeskTopBackground = evt.getY();
    }//GEN-LAST:event_drop_zone_panelMousePressed

    private void drop_zone_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drop_zone_panelMouseClicked
        // TODO add your handling code here:
        hideImageOptions();

    }//GEN-LAST:event_drop_zone_panelMouseClicked

    private void drop_zone_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drop_zone_panelMouseDragged
//        int x = evt.getXOnScreen();
//        int y = evt.getYOnScreen();
//        x2 = x;
//        y2 = y;
//        this.setLocation(x - xMouseInDeskTopBackground, y - yMouseInDeskTopBackground);
    }//GEN-LAST:event_drop_zone_panelMouseDragged
    private void PickColor() {
        Color newColor = jColorChooser1.showDialog(null, "Choose a color", Color.RED);
        int jlabel_id = Integer.parseInt(Jlabel_OPTIONS_LABEL_ID.getText());
        Map<String, Object> jlabel_LABEL_STAT = List_jlabels_statField_label.get(jlabel_id);

        jlabels[jlabel_id].setForeground(newColor);
        int newWidth = jlabels[jlabel_id].getWidth();
        int newHeight = jlabels[jlabel_id].getHeight();
        int X = jlabels[jlabel_id].getX();
        int Y = jlabels[jlabel_id].getY();
        int FontSize = opt.ConvertObjectToInt(jlabel_LABEL_STAT.get("FontSize"));

        SetXYWHFIC_TEXT(X, Y, newWidth, newHeight, FontSize, jlabel_id, newColor);
        drop_zone_panel.validate();
        drop_zone_panel.repaint();
        System.out.println("COLORPICK: " + newColor);
    }

    private void SaveProject() {
        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): "
                    + jFileChooser1.getCurrentDirectory());
            System.out.println("getSelectedFile() : "
                    + jFileChooser1.getSelectedFile());
            String namaID = "TEST";
            String namaProject = "ICONBOX";
            String fileName = "SampleIcon";
            Export_Script exp = new Export_Script(fileName, namaID, namaProject, jFileChooser1.getSelectedFile());
            exp.CreateDirectory();
            exp.PutFileINIinPROJECT();
            exp.PutFileImageinRes(sum_Labels, List_jlabels_statField_label, List_jlabels_base_sample);
        } else {
            System.out.println("No Selection ");
        }
    }
    private void checkCustomPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCustomPathActionPerformed
        FILE_OPTIONS.setVisible(false);
        this.SaveProject();
    }//GEN-LAST:event_checkCustomPathActionPerformed

    private void Change_Color_IMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Change_Color_IMGMouseClicked
        hideImageOptions();
        int jlabel_id = Integer.parseInt(Jlabel_OPTIONS_IMG_ID.getText());
        jlabels[jlabel_id].getIcon();
        String fileName = "TempImage" + jlabel_id;
        try {

            BufferedImage img_input = null;
            BufferedImage img = null;
            img_input = ImageIO.read(new File(path_local + fileName + ".png"));
            img = opt.colorImage(img_input, 255, 0, 0);
            int Scale = 0;
            int Pref_Size = 200;
            if (img.getWidth() > img.getHeight()) {
                Scale = img.getWidth() / Pref_Size;
            } else {
                Scale = img.getHeight() / Pref_Size;
            }
            int img_maxwidth = img.getWidth() / Scale;
            int img_maxheight = img.getHeight() / Scale;
            Image dimg = img.getScaledInstance(img_maxwidth, img_maxheight, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);
            jlabels[jlabel_id].setIcon(icon);
            drop_zone_panel.validate();
            drop_zone_panel.repaint();
//        CreateLabelWithImage(fileName, jlabel_id);
        } catch (Exception e) {
            System.out.println("ERR: " + e);
        }

    }//GEN-LAST:event_Change_Color_IMGMouseClicked

    private void RESIZE_LABEL_IMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESIZE_LABEL_IMGMouseClicked
        IMG_OPTIONS.setVisible(false);
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        int jlabel_id = Integer.parseInt(Jlabel_OPTIONS_IMG_ID.getText());
        SETWIDTH_HEIGHT_DIALOG.setVisible(true);
        SETWIDTH_HEIGHT_DIALOG.setLocation(x, y);
        SET_WIDTH_INPUT.setText("" + jlabels[jlabel_id].getWidth());
        SET_HEIGHT_INPUT.setText("" + jlabels[jlabel_id].getHeight());
        RESIZE_ID.setText("" + jlabel_id);
    }//GEN-LAST:event_RESIZE_LABEL_IMGMouseClicked

    private void SAVE_W_H_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVE_W_H_LABELMouseClicked
        SETWIDTH_HEIGHT_DIALOG.setVisible(false);
        int jlabel_id = Integer.parseInt(Jlabel_OPTIONS_IMG_ID.getText());
        int newWidth = Integer.parseInt(SET_WIDTH_INPUT.getText());
        int newHeight = Integer.parseInt(SET_HEIGHT_INPUT.getText());
        int X = jlabels[jlabel_id].getX();
        int Y = jlabels[jlabel_id].getY();
        Map<String, Object> jlabel_file_img = List_jlabels_base_sample.get(jlabel_id);
        int TypeData = opt.ConvertObjectToInt(jlabel_file_img.get("typeData"));
        File fileData = opt.ConvertObjectToFile(jlabel_file_img.get("filePath"));
        String fileName = null;
        if (TypeData == 1) {
            fileName = fileData.getPath();
        }

        jlabels[jlabel_id].setBounds(X, Y, newWidth, newHeight);
        jlabels[jlabel_id].setIcon(opt.Update_Label_PROPS(fileName, newWidth, newHeight));

        SetXYWH_IMG(X, Y, newWidth, newHeight, jlabel_id);
        drop_zone_panel.validate();
        drop_zone_panel.repaint();

    }//GEN-LAST:event_SAVE_W_H_LABELMouseClicked

    private void EXIT_APPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXIT_APPMouseClicked
        int EXIT_RESPONSE = JOptionPane.showConfirmDialog(jPanel1, "Are you sure want to exit app ? ", "Yes, Confirm", JOptionPane.YES_NO_OPTION);
        if (EXIT_RESPONSE == JOptionPane.YES_OPTION) {
            dispose();
            Launcher launcher = new Launcher();
            launcher.setVisible(true);
            launcher.setUndecorated(true);
            launcher.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_EXIT_APPMouseClicked

    private void FILE_SAVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FILE_SAVEMouseClicked
        this.SaveProject();
        FILE_OPTIONS.setVisible(false);
    }//GEN-LAST:event_FILE_SAVEMouseClicked

    private void Change_Color_Label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Change_Color_Label1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Change_Color_Label1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
// FILE_OPTIONS.setLocation(x, y);
INSERT_OPTIONS.setVisible(false);
        FILE_OPTIONS.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void INSERT_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INSERT_LABELMouseClicked
        INSERT_OPTIONS.setVisible(true);
        FILE_OPTIONS.setVisible(false);
    }//GEN-LAST:event_INSERT_LABELMouseClicked

    private void IN_RAM_METER_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IN_RAM_METER_LABELMouseClicked
        try {
            Label_Drop_Image.setText(null);
            INSERT_OPTIONS.setVisible(false);
            String typeText = "RAM";
            Set_jlabel_Basic_Text(typeText, sum_Labels);
            CreateLabelWithText(sum_Labels);
            sum_Labels += 1;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_IN_RAM_METER_LABELMouseClicked

    private void IN_CPU_METER_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IN_CPU_METER_LABELMouseClicked
        try {
            Label_Drop_Image.setText(null);
            INSERT_OPTIONS.setVisible(false);
            System.out.println("Angka: " + sum_Labels);
            String typeText = "CPU";
            Set_jlabel_Basic_Text(typeText, sum_Labels);
            CreateLabelWithText(sum_Labels);
            sum_Labels += 1;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_IN_CPU_METER_LABELMouseClicked

    private void Change_Color_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Change_Color_LABELMouseClicked
        this.PickColor();
    }//GEN-LAST:event_Change_Color_LABELMouseClicked

    private void SAVE_FONTSTYLING_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVE_FONTSTYLING_LABELMouseClicked
        SETFONTSIZE_DIALOG.setVisible(false);
        int fontSize = Integer.parseInt(SET_FONTSIZE_INPUT.getText());
//        Color newColor = jColorChooser1.showDialog(null, "Choose a color", Color.RED);
        Font newFont = new Font("Times New Roman", Font.PLAIN, fontSize);
        int jlabel_id = Integer.parseInt(Jlabel_OPTIONS_LABEL_ID.getText());
        Map<String, Object> jlabel_LABEL_STAT = List_jlabels_statField_label.get(jlabel_id);

        jlabels[jlabel_id].setFont(newFont);
        int X = jlabels[jlabel_id].getX();
        int Y = jlabels[jlabel_id].getY();
//        int FontSize = opt.ConvertObjectToInt(jlabel_LABEL_STAT.get("FontSize"));
        Color oldColor = opt.ConvertObjectToColor(jlabel_LABEL_STAT.get("FontColor"));
        int MaxWidth = (3 * fontSize);
        int MaxHeight = (2 * fontSize) - 4;
        System.out.println("DTAA:"+MaxHeight+":?"+MaxWidth);
        jlabels[jlabel_id].setBounds(X, Y, MaxWidth, MaxHeight);
        SetXYWHFIC_TEXT(X, Y, MaxWidth, MaxHeight, fontSize, jlabel_id, oldColor);
        drop_zone_panel.validate();
        drop_zone_panel.repaint();
    }//GEN-LAST:event_SAVE_FONTSTYLING_LABELMouseClicked

    private void Font_Styling_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Font_Styling_LabelMouseClicked
        SETFONTSIZE_DIALOG.setVisible(true);
        LABEL_OPTIONS.setVisible(false);

    }//GEN-LAST:event_Font_Styling_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                new Main_Frame().setVisible(true);
            }
        });
    }
// add image with label

    private void onMouseClicked(MouseEvent e) {
        for (int i = 0; i < jlabels.length; i++) {
            if (e.getSource() == jlabels[i]) {
                System.out.println("Label" + i + "was clicked");
            }
        }
    }

    private void hideImageOptions() {
        IMG_OPTIONS.setVisible(false);
        FILE_OPTIONS.setVisible(false);
        LABEL_OPTIONS.setVisible(false);
        SETWIDTH_HEIGHT_DIALOG.setVisible(false);
        for (int i = 0; i < sum_Labels; i++) {
            Border empty = BorderFactory.createEmptyBorder();
            jlabels[i].setBorder(empty);
        }
    }

    public void AddXYWH_IMG(int X, int Y, int W, int H, int id) {
        Map<String, Object> jlabels_stat = new HashMap<>();
        jlabels_stat.put("X", X);
        jlabels_stat.put("Y", Y);
        jlabels_stat.put("W", W);
        jlabels_stat.put("H", H);
        List_jlabels_statField_label.add(id, jlabels_stat);
    }

    public void SetXYWH_IMG(int X, int Y, int W, int H, int id) {
        Map<String, Object> jlabels_stat = new HashMap<>();
        System.out.println("Set XY: " + X + " :" + Y);
        jlabels_stat.put("X", X);
        jlabels_stat.put("Y", Y);
        jlabels_stat.put("W", W);
        jlabels_stat.put("H", H);
        List_jlabels_statField_label.set(id, jlabels_stat);
    }

    public void AddXYWHFIC_TEXT(int X, int Y, int W, int H, int fontSize, int id, Color font_color) {
        Map<String, Object> jlabels_stat = new HashMap<>();
        jlabels_stat.put("X", X);
        jlabels_stat.put("Y", Y);
        jlabels_stat.put("W", W);
        jlabels_stat.put("H", H);
        jlabels_stat.put("FontSize", fontSize);
        jlabels_stat.put("FontColor", font_color);
        List_jlabels_statField_label.add(id, jlabels_stat);
    }

    public void SetXYWHFIC_TEXT(int X, int Y, int W, int H, int fontSize, int id, Color font_color) {
        Map<String, Object> jlabels_stat = new HashMap<>();
        System.out.println("Set XY: " + X + " :" + Y);
        jlabels_stat.put("X", X);
        jlabels_stat.put("Y", Y);
        jlabels_stat.put("W", W);
        jlabels_stat.put("H", H);
        jlabels_stat.put("FontSize", fontSize);
        jlabels_stat.put("FontColor", font_color);
        List_jlabels_statField_label.set(id, jlabels_stat);
    }

    public void Set_jlabel_Basic(File filePath, int id) {
//        Map<String, File> jlabels_stat = new HashMap<>();
        Map<String, Object> jlabels_stat = new HashMap<>();
        jlabels_stat.put("filePath", filePath);
        jlabels_stat.put("typeData", 1);
        // 1 for image
        // 2 for label
        System.out.println("ERR6");
        List_jlabels_base_sample.add(id, jlabels_stat);
    }

    public void Set_jlabel_Basic_Text(String textType, int id) {
        Map<String, Object> jlabels_stat = new HashMap<>();
        jlabels_stat.put("textType", textType);
        jlabels_stat.put("typeData", 2);
        // 1 for image
        // 2 for label
        List_jlabels_base_sample.add(id, jlabels_stat);
    }

    public void CreateLabelWithImage(int id) {
        try {
            System.out.println("IM CALLED?");
            BufferedImage img = null;

            Map<String, Object> jlabel_file_img = List_jlabels_base_sample.get(id);
            int TypeData = opt.ConvertObjectToInt(jlabel_file_img.get("typeData"));
            File fileData = opt.ConvertObjectToFile(jlabel_file_img.get("filePath"));
            String fileName = null;
            if (TypeData == 1) {
                fileName = fileData.getPath();
            }

            img = ImageIO.read(fileData);
            int Scale = 0;
            int Pref_Size = 200;
            if (img.getWidth() > img.getHeight()) {
                Scale = img.getWidth() / Pref_Size;
            } else {
                Scale = img.getHeight() / Pref_Size;
            }
            int img_maxwidth = img.getWidth() / Scale;
            int img_maxheight = img.getHeight() / Scale;
            Image dimg = img.getScaledInstance(img_maxwidth, img_maxheight, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);
            jlabels[id] = new JLabel("Label" + sum_Labels);
            jlabels[id].setIcon(icon);
            jlabels[id].setBounds(1, 1 + (sum_Labels * 20), img_maxwidth, img_maxheight);
            this.AddXYWH_IMG(jlabels[id].getX(), jlabels[id].getY(), img_maxwidth, img_maxheight, id);
            jlabels[id].setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
            jlabels[id].addMouseMotionListener(new MouseMotionListener() {
                @Override
                public void mouseDragged(MouseEvent e) {
                    int x = e.getXOnScreen();
                    int y = e.getYOnScreen();
                    SetXYWH_IMG(jlabels[id].getX(), jlabels[id].getY(), jlabels[id].getWidth(), jlabels[id].getHeight(), id);

                    jlabels[id].setLocation((x - x2) - (xImage_POS - xMouseInDeskTopBackground), (y - y2) - (yImage_POS - yMouseInDeskTopBackground));
                }

                @Override
                public void mouseMoved(MouseEvent e) {
                }
            });
            jlabels[id].addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {

                    Border grayBorder = BorderFactory.createLineBorder(Color.GRAY, 2, true);
                    jlabels[id].setBorder(grayBorder);
                    if (SwingUtilities.isRightMouseButton(e) || e.isControlDown()) {
                        int x = e.getXOnScreen();
                        int y = e.getYOnScreen();
                        IMG_OPTIONS.setLocation(x, y);
                        IMG_OPTIONS.setVisible(true);
                        Jlabel_OPTIONS_IMG_ID.setText("" + id);
                    }
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    xImage_POS = e.getX();
                    yImage_POS = e.getY();
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                }

                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
            drop_zone_panel.add(jlabels[id]);
            drop_zone_panel.validate();
            drop_zone_panel.repaint();
        } catch (Exception e) {
        }
    }

    public void CreateLabelWithText(int id) {
        try {
            System.out.println("LABEL ID: " + id);
            Map<String, Object> jlabel_file_texts = List_jlabels_base_sample.get(id);
            jlabels[id] = new JLabel("Label" + sum_Labels);
            int fontSizeDefault = 16;
            Font defaultFont = new Font("Times New Roman", Font.PLAIN, fontSizeDefault);
//            jlabel_file_texts.get("textType")
            Color watna = new Color(id, id, id);
            switch (opt.ConvertObjectToString(jlabel_file_texts.get("textType"))) {
                case "RAM":
                    jlabels[id].setText("RAM");
                    jlabels[id].setForeground(Color.red);
                    jlabels[id].setFont(defaultFont);
                    break;
                case "CPU":
                    jlabels[id].setText("CPU");
                    jlabels[id].setForeground(Color.red);
                    jlabels[id].setFont(defaultFont);
                    break;
                default:
                    jlabels[id].setText("String Text");
                    jlabels[id].setForeground(Color.red);
                    jlabels[id].setBackground(Color.red);
                // code block
            }
            int MaxWidth = (3 * fontSizeDefault);
            int MaxHeight = (2 * fontSizeDefault) - 4;
            jlabels[id].setBounds(5 * fontSizeDefault, ((sum_Labels + 1) * 4 * fontSizeDefault), MaxWidth, MaxHeight);
            this.AddXYWHFIC_TEXT(jlabels[id].getX(), jlabels[id].getY(), MaxWidth, MaxHeight, fontSizeDefault, id, Color.red);
            jlabels[id].setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
            jlabels[id].addMouseMotionListener(new MouseMotionListener() {
                @Override
                public void mouseDragged(MouseEvent e) {
                    int x = e.getXOnScreen();
                    int y = e.getYOnScreen();
                    SetXYWHFIC_TEXT(jlabels[id].getX(), jlabels[id].getY(), MaxWidth, MaxHeight, fontSizeDefault, id, Color.red);
                    jlabels[id].setLocation((x - x2) - (xImage_POS - xMouseInDeskTopBackground), (y - y2) - (yImage_POS - yMouseInDeskTopBackground));
                }

                @Override
                public void mouseMoved(MouseEvent e) {
                }
            });
            jlabels[id].addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {

                    Border grayBorder = BorderFactory.createLineBorder(Color.GRAY, 2, true);
                    jlabels[id].setBorder(grayBorder);
                    if (SwingUtilities.isRightMouseButton(e) || e.isControlDown()) {
                        int x = e.getXOnScreen();
                        int y = e.getYOnScreen();
                        LABEL_OPTIONS.setLocation(x, y);
                        LABEL_OPTIONS.setVisible(true);
                        Jlabel_OPTIONS_LABEL_ID.setText("" + id);
                    }
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    xImage_POS = e.getX();
                    yImage_POS = e.getY();
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                }

                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
            drop_zone_panel.add(jlabels[id]);
            drop_zone_panel.validate();
            drop_zone_panel.repaint();
        } catch (Exception e) {
        }
    }
// Something Called JPANEL

    public class DropPane extends JPanel {

        private DropTarget dropTarget;
        private DropTargetHandler dropTargetHandler;
        private Point dragPoint;

        private boolean dragOver = false;
        private BufferedImage target;

//        private JLabel message;
        public DropPane() {
            System.out.println("THIS IS PANE");
            try {
                target = ImageIO.read(new File("TestImage.png"));
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            setLayout(new GridBagLayout());
//            messageText = new JLabel();
//            messageText.setFont(messageText.getFont().deriveFont(Font.BOLD, 24));
//            add(messageText);

        }

        @Override
        public Dimension getPreferredSize() {
            return new Dimension(400, 400);
        }

        protected DropTarget getMyDropTarget() {
            if (dropTarget == null) {
                dropTarget = new DropTarget(this, DnDConstants.ACTION_COPY_OR_MOVE, null);
            }
            return dropTarget;
        }

        protected DropTargetHandler getDropTargetHandler() {
            if (dropTargetHandler == null) {
                dropTargetHandler = new DropTargetHandler();
            }
            return dropTargetHandler;
        }

        @Override
        public void addNotify() {
            super.addNotify();
            System.out.println("THIS IS NOTIFY");
            try {
                getMyDropTarget().addDropTargetListener(getDropTargetHandler());
            } catch (TooManyListenersException ex) {
                ex.printStackTrace();
            }
        }

        @Override
        public void removeNotify() {
            super.removeNotify();
            getMyDropTarget().removeDropTargetListener(getDropTargetHandler());
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (dragOver) {
                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setColor(new Color(0, 255, 0, 64));
                g2d.fill(new Rectangle(getWidth(), getHeight()));
                if (dragPoint != null && target != null) {
                    int x = dragPoint.x - 12;
                    int y = dragPoint.y - 12;
                    g2d.drawImage(target, x, y, this);
                }
                g2d.dispose();
            }
        }

        protected void importFiles(final List files) {
            Runnable run = new Runnable() {
                @Override
                public void run() {
                    int jumlahSize = List_jlabels_base_sample.size();
//                    sum_Labels =jumlahSize;
                    if (sum_Labels <= 10) {
                        try {
                            Label_Drop_Image.setText(null);
                            System.out.println("Angka LIST LABEL: " + jumlahSize);
                            System.out.println("files.size(): " + files.size());
                            System.out.println("sum_Labels " + sum_Labels);
                            if (sum_Labels == 0) {
                                for (int i = 0; i < files.size(); i++) {
                                    System.out.println("ERR!");
                                    Set_jlabel_Basic((File) files.get(i), i);
                                    CreateLabelWithImage(i);
                                }
                                sum_Labels = files.size();
                            } else {
                                for (int i = sum_Labels; i < (sum_Labels + files.size()); i++) {
                                    System.out.println("ERR2");
                                    Set_jlabel_Basic((File) files.get(i - sum_Labels), i);
                                    System.out.println("ERR3");
                                    CreateLabelWithImage(i);
                                    System.out.println("ERR4");
                                }
                                sum_Labels += files.size();
                            }

//                        File pathToFile = new File("TestImage.png");
//                        boolean exists = pathToFile.exists();
//                        long fileSize = pathToFile.length();
//
//                        BufferedImage img = null;
//                        img = ImageIO.read(new File(path_local + "TestImage.png"));
//                        int img_maxwidth = img.getWidth() % 400;
//                        int img_maxheight = img.getHeight() % 400;
//                        Image dimg = img.getScaledInstance(img_maxwidth, img_maxheight, Image.SCALE_SMOOTH);
//                        ImageIcon icon = new ImageIcon(dimg);
//                        Image_1.setIcon(icon);
//                        Image_1.setBounds(0, 0, img_maxwidth, img_maxheight);
//                            FileTitle.setText("You dropped " + files.size());
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else {
                        alertBox.showMessageDialog(jFrame1, "Maximum 10 image", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                }
            };
            SwingUtilities.invokeLater(run);
        }

        protected class DropTargetHandler implements DropTargetListener {

            protected void processDrag(DropTargetDragEvent dtde) {
                if (dtde.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                    dtde.acceptDrag(DnDConstants.ACTION_COPY);
                } else {
                    dtde.rejectDrag();
                }
            }

            @Override
            public void dragEnter(DropTargetDragEvent dtde) {
                processDrag(dtde);
                SwingUtilities.invokeLater(new DragUpdate(true, dtde.getLocation()));
                repaint();
            }

            @Override
            public void dragOver(DropTargetDragEvent dtde) {
                processDrag(dtde);
                SwingUtilities.invokeLater(new DragUpdate(true, dtde.getLocation()));
                repaint();
            }

            @Override
            public void dropActionChanged(DropTargetDragEvent dtde) {
            }

            @Override
            public void dragExit(DropTargetEvent dte) {
                SwingUtilities.invokeLater(new DragUpdate(false, null));
                repaint();
            }

            @Override
            public void drop(DropTargetDropEvent dtde) {
                String file_address = "/file/id/namaProject/@Resources";
                Path path = Paths.get(file_address);
                System.out.println("THIS IS DROP");

                SwingUtilities.invokeLater(new DragUpdate(false, null));

                Transferable transferable = dtde.getTransferable();

                if (dtde.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                    dtde.acceptDrop(dtde.getDropAction());
                    try {
                        List transferData = (List) transferable.getTransferData(DataFlavor.javaFileListFlavor);
//                        jLabel1.setIcon(new ImageIcon(transferData.get(0)));
                        importFiles(transferData);
                        dtde.dropComplete(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
//                    if (transferable.isDataFlavorSupported(DataFlavor.imageFlavor)) {
//                        System.out.println("THIS IS DROP IMAGE");
//                        try {
//                            Image image = (Image) dtd
//                        DataFlavor.imageFlavor
//                            );
//                        jLabel1.setIcon(new ImageIcon(image));
//                        } catch (UnsupportedFlavorException | IOException e) {
//                            e.printStackTrace();
//                        }
//                    }

//                    try {
////                        if (transferable.isDataFlavorSupported(DataFlavor.imageFlavor)) {
////                            Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
////                            BufferedImage img = (BufferedImage) cb.getData(DataFlavor.imageFlavor);
////                            System.out.println("FILE IMAGE");
////                            File file = new File("newimage.png");
////                            ImageIO.write(img, "png", file);
////                        }
//                        List<File> transferData = (List<File>) transferable.getTransferData(DataFlavor.javaFileListFlavor);
//                        if (transferData != null && transferData.size() > 0) {
//                            System.out.println("FILE IMAGE" + transferData.get(0));
//                            File f = transferData.get(0);
//                            ImageIcon iIcon = new ImageIcon(f.getAbsolutePath());
//                            image = iIcon.getImage();
//                            jLabel1.setIcon(iIcon);
////                            System.out.println("FILE IMAGEA");
////                            FileOutputStream fout = new FileOutputStream("gambar1.png");
////                            fout.write(data);
////                            fout.close();
////                            input.close();
////                            BufferedImage img = ;
////                            File source = new File(transferData.get(0));
////                            File dest = new File(file_address);
////                            FileUtils.copyDirectory(source, dest);
//
//                            importFiles(transferData);
//                            dtde.dropComplete(true);
//                        }
//
//                    } catch (Exception ex) {
//                        ex.printStackTrace();
//                    }
                } else {
                    dtde.rejectDrop();
                }
            }
        }

        public class DragUpdate implements Runnable {

            private boolean dragOver;
            private Point dragPoint;

            public DragUpdate(boolean dragOver, Point dragPoint) {
                this.dragOver = dragOver;
                this.dragPoint = dragPoint;
            }

            @Override
            public void run() {
                DropPane.this.dragOver = dragOver;
                DropPane.this.dragPoint = dragPoint;
                DropPane.this.repaint();
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel COLOR_PICKER_PANEL;
    private javax.swing.JLabel Change_Color_IMG;
    private javax.swing.JLabel Change_Color_LABEL;
    private javax.swing.JLabel Change_Color_Label1;
    private javax.swing.JPanel Choose_File_Panel;
    private javax.swing.JLabel EXIT_APP;
    private javax.swing.JPanel FILE_LABEL;
    private javax.swing.JPanel FILE_OPTIONS;
    private javax.swing.JLabel FILE_SAVE;
    private javax.swing.JLabel FONTSTYLING_ID;
    private javax.swing.JLabel Font_Styling_Label;
    private javax.swing.JPanel IMG_OPTIONS;
    private javax.swing.JLabel INSERT_LABEL;
    private javax.swing.JPanel INSERT_OPTIONS;
    private javax.swing.JLabel IN_CPU_METER_LABEL;
    private javax.swing.JLabel IN_RAM_METER_LABEL;
    private javax.swing.JLabel Jlabel_OPTIONS_ID1;
    private javax.swing.JLabel Jlabel_OPTIONS_ID2;
    private javax.swing.JLabel Jlabel_OPTIONS_IMG_ID;
    private javax.swing.JLabel Jlabel_OPTIONS_LABEL_ID;
    private javax.swing.JPanel LABEL_OPTIONS;
    private javax.swing.JLabel Label_Drop_Image;
    private javax.swing.JLabel RESIZE_ID;
    private javax.swing.JLabel RESIZE_LABEL_IMG;
    private javax.swing.JLabel SAVE_FONTSTYLING_LABEL;
    private javax.swing.JLabel SAVE_W_H_LABEL;
    private javax.swing.JPanel SETFONTSIZE_DIALOG;
    private javax.swing.JPanel SETWIDTH_HEIGHT_DIALOG;
    private javax.swing.JTextField SET_FONTSIZE_INPUT;
    private javax.swing.JTextField SET_HEIGHT_INPUT;
    private javax.swing.JTextField SET_HEIGHT_INPUT1;
    private javax.swing.JTextField SET_WIDTH_INPUT;
    private javax.swing.JToggleButton checkCustomPath;
    private javax.swing.JPanel drop_zone_panel;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
